// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocviyqiwdxtrcjvfnyhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jdml5cWl3ZHh0cmNqdmZueWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDk0NzIsImV4cCI6MjA3NDM4NTQ3Mn0.VtNQGnupV71rXI7QcL9m9eavNe8y5y4DSdDAzb_k22Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});